import type {
  AppConfig,
  DatabaseConnectionConfig,
  ServerInstanceConfig,
  ServerPropertiesConfig
} from '../../shared/types';

export const SERVER_ID_PATTERN = /^[a-zA-Z0-9_-]+$/;

export function assertValidId(id: string, label = 'ID'): void {
  if (!id.trim()) {
    throw new Error(`${label} 不能为空`);
  }
  if (!SERVER_ID_PATTERN.test(id)) {
    throw new Error(`${label} 只允许字母、数字、短横线和下划线`);
  }
}

export function assertUniqueServer(config: AppConfig, server: Pick<ServerInstanceConfig, 'id' | 'name' | 'workdir'>): void {
  assertValidId(server.id, '实例 ID');
  if (!server.name.trim()) {
    throw new Error('实例名称不能为空');
  }
  if (!server.workdir.trim()) {
    throw new Error('工作目录不能为空');
  }
  if (config.servers.some((item) => item.id === server.id)) {
    throw new Error('实例 ID 已存在');
  }
  if (config.servers.some((item) => item.name.trim() === server.name.trim())) {
    throw new Error('实例名称已存在');
  }
  const normalizedWorkdir = server.workdir.trim().toLowerCase();
  if (config.servers.some((item) => item.workdir.trim().toLowerCase() === normalizedWorkdir)) {
    throw new Error('该工作目录已经绑定到其他实例');
  }
}

export function assertUniqueDatabase(config: AppConfig, database: Pick<DatabaseConnectionConfig, 'id' | 'name'>): void {
  assertValidId(database.id, '数据库连接 ID');
  if (!database.name.trim()) {
    throw new Error('数据库连接名称不能为空');
  }
  if (config.databases.some((item) => item.id === database.id)) {
    throw new Error('数据库连接 ID 已存在');
  }
  if (config.databases.some((item) => item.name.trim() === database.name.trim())) {
    throw new Error('数据库连接名称已存在');
  }
}

export function splitCommandLine(value = ''): string[] {
  const result: string[] = [];
  const pattern = /"([^"\\]*(?:\\.[^"\\]*)*)"|'([^'\\]*(?:\\.[^'\\]*)*)'|[^\s]+/g;
  for (const match of value.matchAll(pattern)) {
    result.push((match[1] ?? match[2] ?? match[0]).replace(/\\"/g, '"').replace(/\\'/g, "'"));
  }
  return result;
}

export function defaultServerProperties(): ServerPropertiesConfig {
  return {
    serverPort: 25565,
    onlineMode: true,
    motd: 'DreamStar Server',
    maxPlayers: 2026,
    viewDistance: 10,
    simulationDistance: 10,
    enableCommandBlock: false,
    allowFlight: false,
    difficulty: 'normal',
    gamemode: 'survival',
    pvp: true,
    spawnProtection: 16
  };
}

export function serializeServerProperties(properties: ServerPropertiesConfig): string {
  const lines = [
    '# Generated by DreamStar Server Manager',
    `server-port=${properties.serverPort}`,
    `online-mode=${properties.onlineMode}`,
    `motd=${properties.motd}`,
    `max-players=${properties.maxPlayers}`,
    `view-distance=${properties.viewDistance}`,
    `simulation-distance=${properties.simulationDistance}`,
    `enable-command-block=${properties.enableCommandBlock}`,
    `allow-flight=${properties.allowFlight}`,
    `difficulty=${properties.difficulty}`,
    `gamemode=${properties.gamemode}`,
    `pvp=${properties.pvp}`,
    `spawn-protection=${properties.spawnProtection}`
  ];
  return `${lines.join('\n')}\n`;
}

export function mergeServerProperties(existing: string, generated: string): string {
  const existingLines = existing.split(/\r?\n/);
  const existingKeys = new Set(
    existingLines
      .map((line) => line.trim())
      .filter((line) => line && !line.startsWith('#') && line.includes('='))
      .map((line) => line.split('=')[0])
  );

  const missingLines = generated
    .split(/\r?\n/)
    .filter((line) => {
      const trimmed = line.trim();
      if (!trimmed || trimmed.startsWith('#') || !trimmed.includes('=')) {
        return false;
      }
      return !existingKeys.has(trimmed.split('=')[0]);
    });

  if (missingLines.length === 0) {
    return existing.endsWith('\n') ? existing : `${existing}\n`;
  }

  const suffix = ['# Added by DreamStar Server Manager', ...missingLines].join('\n');
  return `${existing.trimEnd()}\n${suffix}\n`;
}

const DANGEROUS_SQL = /^(insert|update|delete|drop|truncate|alter|create|grant|revoke)\b/i;

export function isDangerousSql(sql: string): boolean {
  return DANGEROUS_SQL.test(sql.trim());
}

export function getSqlWarning(sql: string): string | undefined {
  const normalized = sql.trim();
  if (/^select\s+\*\s+from\s+/i.test(normalized) && !/\blimit\s+\d+/i.test(normalized)) {
    return 'SELECT * 未包含 LIMIT，建议先限制返回行数。';
  }
  return undefined;
}

const DANGEROUS_REDIS = new Set(['DEL', 'FLUSHDB', 'FLUSHALL', 'CONFIG', 'SHUTDOWN', 'EVAL']);

export function isDangerousRedisCommand(command: string): boolean {
  const name = command.trim().split(/\s+/)[0]?.toUpperCase();
  return DANGEROUS_REDIS.has(name);
}
